name: Daily Android Publish CI

on:
  schedule:
    - cron: '0 8 * * *'  # 每天 UTC 时间 8:00 执行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
    - uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: 21

    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - uses: pnpm/action-setup@v4

    - name: Dependencis install
      run: |
        deno task init && deno task dev
